### ISSUE TITLE
go vet has issues

### ISSUE THREAD

**Issue by shane-ns1** [PowerDNS/lmdb-go#20]
I followed the instructions for a PR in [CONTRIBUTING.md](/PowerDNS/lmdb-go/blob/master/CONTRIBUTING.md), and when I ran `go vet` it raised a few issues.

These are:
```
# github.com/PowerDNS/lmdb-go/lmdbscan
lmdbscan/scanner_test.go:88:3: *github.com/PowerDNS/lmdb-go/internal/lmdbtest.SimpleItem struct literal uses unkeyed fields
```

This for like 50 lines.

And:

```
# github.com/PowerDNS/lmdb-go/cmd/lmdb_stat
cmd/lmdb_stat/main.go:245:44: possible misuse of reflect.SliceHeader
```

**Comment by wojas** [comment]
Thank you for these contributions! All have been merged.
