### ISSUE TITLE
Build error targeting linux on macOS

### ISSUE THREAD

**Issue by dtonon** [PowerDNS/lmdb-go#33]
PowerDNS/lmdb-go is used by https://github.com/bitvora/wot-relay, and I'm trying to compile it targeting linux/amd64 on macOS:

```
GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=$(git describe --tags --always)"
```

I get this error:

```
github.com/PowerDNS/lmdb-go/lmdb: build constraints exclude all Go files in /Users/x/go/pkg/mod/github.com/!power!d!n!s/lmdb-go@v1.9.2/lmdb
```

If I target macOS, it compiles without any problem.

Any help, please?

**Comment by wojas** [comment]
Cross compiling Go code does not work out of the box with CGo dependencies, like lmdb-go. You will have to build it on the target machine, or in a container using Docker for Mac.

**Comment by dtonon** [comment]
Thank you @wojas, I will try that!

**Comment by dtonon** [comment]
I confirm that I was able to use Docker to compile correctly.
